version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    target-branch: nightly
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Jakarta
    open-pull-requests-limit: 5
    groups:
      python-runtime-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch
      python-development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
    labels:
      - dependencies
      - python
    commit-message:
      prefix: deps

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: nightly
    schedule:
      interval: monthly
      time: "03:30"
      timezone: Asia/Jakarta
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: ci
