#!/usr/bin/env node
import { createHash } from 'node:crypto';import { access,readFile,stat } from 'node:fs/promises';import path from 'node:path';import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),repository=path.resolve(root,'..','..');const json=async(relative)=>JSON.parse(await readFile(path.join(root,relative),'utf8'));const upstream=await json('UPSTREAM.json'),product=await json('product.template.json'),extension=await json('extension/package.json'),providers=await json('extension/providers.json'),patches=await json('patches/vscodium/PATCHES.json');const assert=(value,message)=>{if(!value)throw new Error(message)};
assert(/^[0-9a-f]{40}$/.test(upstream.commit),'upstream commit not pinned');assert(/^[0-9a-f]{64}$/.test(upstream.archiveSha256),'upstream hash invalid');assert(patches.sourceCommit===upstream.patchSource.commit&&patches.sourceArchiveSha256===upstream.patchSource.archiveSha256,'patch provenance mismatch');assert(Object.keys(patches.files||{}).length>=60,'patch set incomplete');for(const [name,expected] of Object.entries(patches.files)){const actual=createHash('sha256').update(await readFile(path.join(root,'patches/vscodium',name))).digest('hex');assert(actual===expected,`patch digest mismatch: ${name}`);}
assert(product.nameLong==='BibzCode IDE'&&product.applicationName==='bibzcode','identity mismatch');assert(product.extensionsGallery?.serviceUrl==='https://open-vsx.org/vscode/gallery','registry mismatch');assert(product.enableTelemetry===false,'telemetry enabled');const serialized=JSON.stringify(product).toLowerCase();for(const forbidden of ['marketplace.'+'visualstudio.com','copilot_internal','tmpfiles'+'.org'])assert(!serialized.includes(forbidden),`forbidden service: ${forbidden}`);
assert(extension.publisher==='bibzcode'&&extension.capabilities?.untrustedWorkspaces?.supported===false,'extension security metadata invalid');const commands=(extension.contributes?.commands||[]).map((item)=>item.command);assert(commands.length>=17&&new Set(commands).size===commands.length,'commands missing/duplicate');for(const command of ['bibzcode.openAgent','bibzcode.setupRuntime','bibzcode.providers.setKey','bibzcode.sessions.resume','bibzcode.sessions.search','bibzcode.sessions.pin','bibzcode.sessions.context','bibzcode.sessions.compact'])assert(commands.includes(command),`missing ${command}`);const views=extension.contributes?.views?.bibzcode||[];assert(views.some((v)=>v.id==='bibzcode.agent'&&v.type==='webview')&&views.some((v)=>v.id==='bibzcode.providers')&&views.some((v)=>v.id==='bibzcode.sessions'),'views missing');
assert(providers.length===8&&new Set(providers.map((p)=>p.id)).size===8,'provider list invalid');for(const provider of providers){assert(/^[a-z][a-z0-9_-]+$/.test(provider.id),`provider id invalid: ${provider.id}`);assert(/^[A-Z][A-Z0-9_]+_API_KEY$/.test(provider.env),`provider env invalid: ${provider.id}`);assert(provider.models.includes(provider.defaultModel),`default model missing: ${provider.id}`);}
for(const file of ['extension/extension.js','extension/lib.js','extension/media/activity.svg','assets/icon.png','assets/icon.ico','assets/icon.icns','../../bibzcode/ide_bridge.py','security-lock-overrides.json']){const location=path.resolve(root,file);await access(location);assert((await stat(location)).size>0,`empty file: ${file}`);}const source=await readFile(path.join(root,'extension/extension.js'),'utf8');assert(!source.includes('shell: true')&&source.includes('shell: false'),'shell process boundary invalid');assert(source.includes('context.secrets.store'),'SecretStorage missing');assert(source.includes('workspace.isTrusted'),'workspace trust missing');assert(source.includes("default-src 'none'"),'webview CSP missing');assert(source.includes("'-m', 'bibzcode.ide_bridge'"),'bridge missing');assert(source.includes('BIBZCODE_IDE_PROTOCOL')&&source.includes('vscode.diff'),'authenticated change review missing');assert(source.includes('terminateProcessTree(child)')&&source.includes('options.token.onCancellationRequested'),'process-tree cancellation missing');
try{await access(path.join(repository,'dashboard-react'));throw new Error('private deployment source found');}catch(error){if(error.message.includes('private deployment'))throw error;}console.log(`Overlay verification passed: ${commands.length} commands, ${providers.length} providers, pinned ${upstream.tag}.`);
