#!/usr/bin/env python3
"""Validate public-repository contribution policy using only the standard library."""

from __future__ import annotations

import hashlib
import re
import subprocess
import sys
from pathlib import Path
from urllib.parse import unquote

ROOT = Path(__file__).resolve().parents[1]
REQUIRED = {
    "README.md",
    "CONTRIBUTING.md",
    "CODE_OF_CONDUCT.md",
    "SECURITY.md",
    "SUPPORT.md",
    "GOVERNANCE.md",
    "CHANGELOG.md",
    "docs/DEVELOPMENT.md",
    "docs/i18n/README.md",
    "docs/i18n/README.id.md",
    "docs/i18n/TRANSLATING.md",
    ".github/CODEOWNERS",
    ".github/PULL_REQUEST_TEMPLATE.md",
    ".github/ISSUE_TEMPLATE/config.yml",
    ".github/ISSUE_TEMPLATE/bug_report.yml",
    ".github/ISSUE_TEMPLATE/feature_request.yml",
    ".github/ISSUE_TEMPLATE/question.yml",
}
LINK_RE = re.compile(r"(?<!!)\[[^\]]+\]\(([^)]+)\)")
FORBIDDEN_FILENAMES = {
    ".env",
    "credentials.json",
    "secrets.json",
}
FORBIDDEN_SUFFIXES = (".pem", ".key", ".pyc")


def tracked_files() -> list[str]:
    """Return Git-tracked paths, with a source-archive fallback.

    GitHub and release ZIPs intentionally omit ``.git``. The fallback keeps the
    validator useful in those snapshots while excluding common local/build output.
    """
    try:
        result = subprocess.run(
            ["git", "ls-files", "-z"],
            cwd=ROOT,
            check=True,
            capture_output=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError):
        excluded_parts = {
            ".git",
            ".pytest_cache",
            ".venv",
            "__pycache__",
            "build",
            "dist",
            "node_modules",
        }
        return sorted(
            path.relative_to(ROOT).as_posix()
            for path in ROOT.rglob("*")
            if path.is_file() and not excluded_parts.intersection(path.relative_to(ROOT).parts)
        )
    return [item.decode("utf-8") for item in result.stdout.split(b"\0") if item]


def validate_required(errors: list[str]) -> None:
    for relative in sorted(REQUIRED):
        path = ROOT / relative
        if not path.is_file() or not path.read_text("utf-8").strip():
            errors.append(f"required community file is missing or empty: {relative}")


def validate_tracked_paths(files: list[str], errors: list[str]) -> None:
    for relative in files:
        path = Path(relative)
        lowered = relative.lower()
        if path.parts and path.parts[0].lower() == "dashboard-react":
            errors.append(f"deployment-only dashboard path must not be tracked: {relative}")
        if path.name.lower() in FORBIDDEN_FILENAMES or path.name.lower().startswith(".env."):
            errors.append(f"credential/config file must not be tracked: {relative}")
        if lowered.endswith(FORBIDDEN_SUFFIXES):
            errors.append(f"private key or generated bytecode must not be tracked: {relative}")
        if "service-account" in lowered or "service_account" in lowered or "adminsdk" in lowered:
            errors.append(f"service-account path must not be tracked: {relative}")


def validate_relative_links(files: list[str], errors: list[str]) -> None:
    for relative in files:
        if not relative.lower().endswith(".md"):
            continue
        source = ROOT / relative
        text = source.read_text("utf-8")
        for raw_target in LINK_RE.findall(text):
            target = raw_target.strip().strip("<>").split(maxsplit=1)[0]
            if not target or target.startswith(("#", "http://", "https://", "mailto:")):
                continue
            target_path = unquote(target.split("#", 1)[0])
            if not target_path:
                continue
            resolved = (source.parent / target_path).resolve()
            try:
                resolved.relative_to(ROOT.resolve())
            except ValueError:
                errors.append(f"relative link escapes repository in {relative}: {target}")
                continue
            if not resolved.exists():
                errors.append(f"broken relative link in {relative}: {target}")


def validate_release_integrity(errors: list[str]) -> None:
    checksum_files = sorted((ROOT / "releases").glob("*.sha256.txt"))
    if not checksum_files:
        errors.append("no release checksum file found")
        return
    for checksum_path in checksum_files:
        parts = checksum_path.read_text("utf-8").split()
        if len(parts) < 2 or not re.fullmatch(r"[0-9a-f]{64}", parts[0]):
            errors.append(f"malformed release checksum: {checksum_path.relative_to(ROOT)}")
            continue
        archive = checksum_path.parent / parts[1].lstrip("*")
        if not archive.is_file():
            errors.append(f"checksum archive is missing: {archive.relative_to(ROOT)}")
            continue
        digest = hashlib.sha256(archive.read_bytes()).hexdigest()
        if digest != parts[0]:
            errors.append(f"release checksum mismatch: {archive.relative_to(ROOT)}")


def validate_translations(errors: list[str]) -> int:
    translation_dir = ROOT / "docs" / "i18n"
    translations = sorted(translation_dir.glob("README.*.md"))
    if len(translations) < 40:
        errors.append(f"at least 40 README translations are required; found {len(translations)}")

    root_readme = (ROOT / "README.md").read_text("utf-8")
    index = (translation_dir / "README.md").read_text("utf-8")
    total_languages = len(translations) + 1  # Root README is canonical English.
    if "English (default)" not in root_readme:
        errors.append("root README must identify English as the default language")
    if f"{total_languages} languages" not in root_readme:
        errors.append("root README language count does not match translation files")
    if f"{total_languages} languages" not in index:
        errors.append("translation index language count does not match translation files")
    if (translation_dir / "README.en.md").exists():
        errors.append("English must remain the root default README, not a duplicate translation")

    for path in translations:
        relative_name = path.name
        text = path.read_text("utf-8")
        if not text.startswith("# BibzCode"):
            errors.append(f"translation must start with the BibzCode heading: {relative_name}")
        if "../../README.md" not in text:
            errors.append(f"translation must link to canonical English README: {relative_name}")
        if "bzcli" not in text:
            errors.append(f"translation must preserve the canonical command: {relative_name}")
        if f"]({relative_name})" not in index:
            errors.append(f"translation is missing from language index: {relative_name}")
        if f"docs/i18n/{relative_name}" not in root_readme:
            errors.append(f"translation is missing from root language selector: {relative_name}")

    indonesian = translation_dir / "README.id.md"
    if indonesian.is_file() and len(indonesian.read_text("utf-8")) < 5000:
        errors.append("Bahasa Indonesia README must retain extended documentation coverage")
    return total_languages


def validate_canonical_identity(errors: list[str]) -> None:
    pyproject = (ROOT / "pyproject.toml").read_text("utf-8")
    if 'name = "bibzcode-cli-agent"' not in pyproject:
        errors.append("canonical Python distribution name is missing")
    if 'bzcli = "bibzcode.__main__:main"' not in pyproject:
        errors.append("canonical bzcli entry point is missing")
    if 'dscli = "bibzcode.__main__:main"' not in pyproject:
        errors.append("documented dscli compatibility entry point is missing")

    dependabot = (ROOT / ".github/dependabot.yml").read_text("utf-8")
    if 'package-ecosystem: ""' in dependabot or "package-ecosystem: ''" in dependabot:
        errors.append("Dependabot contains an empty package ecosystem")
    if "target-branch: nightly" not in dependabot:
        errors.append("Dependabot updates must target the integration branch")


def main() -> int:
    errors: list[str] = []
    files = tracked_files()
    validate_required(errors)
    validate_tracked_paths(files, errors)
    validate_relative_links(files, errors)
    validate_release_integrity(errors)
    total_languages = validate_translations(errors)
    validate_canonical_identity(errors)
    if errors:
        print("Contribution policy validation failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1
    print(
        f"Contribution policy validation passed: {len(files)} tracked files, "
        f"{len(REQUIRED)} required community files, {total_languages} languages."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
