#!/usr/bin/env python3
"""Validate public-repository contribution policy using only the standard library."""

from __future__ import annotations

import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path
from urllib.parse import unquote

ROOT = Path(__file__).resolve().parents[1]
REQUIRED = {
    "README.md",
    "CONTRIBUTING.md",
    "CODE_OF_CONDUCT.md",
    "SECURITY.md",
    "SUPPORT.md",
    "GOVERNANCE.md",
    "CHANGELOG.md",
    "docs/DEVELOPMENT.md",
    "docs/i18n/README.md",
    "docs/i18n/README.id.md",
    "docs/i18n/TRANSLATING.md",
    "ide/README.md",
    "ide/package.json",
    "ide/package-lock.json",
    "ide/tests/security.test.ts",
    ".github/workflows/ide-ci.yml",
    ".github/workflows/ide-release.yml",
    ".github/CODEOWNERS",
    ".github/PULL_REQUEST_TEMPLATE.md",
    ".github/ISSUE_TEMPLATE/config.yml",
    ".github/ISSUE_TEMPLATE/bug_report.yml",
    ".github/ISSUE_TEMPLATE/feature_request.yml",
    ".github/ISSUE_TEMPLATE/question.yml",
}
LINK_RE = re.compile(r"(?<!!)\[[^\]]+\]\(([^)]+)\)")
FORBIDDEN_FILENAMES = {
    ".env",
    "credentials.json",
    "secrets.json",
}
FORBIDDEN_SUFFIXES = (".pem", ".key", ".pyc")


def tracked_files() -> list[str]:
    """Return Git-tracked paths, with a source-archive fallback.

    GitHub and release ZIPs intentionally omit ``.git``. The fallback keeps the
    validator useful in those snapshots while excluding common local/build output.
    """
    try:
        result = subprocess.run(
            ["git", "ls-files", "-z"],
            cwd=ROOT,
            check=True,
            capture_output=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError):
        excluded_parts = {
            ".git",
            ".pytest_cache",
            ".venv",
            "__pycache__",
            "build",
            "dist",
            "node_modules",
        }
        return sorted(
            path.relative_to(ROOT).as_posix()
            for path in ROOT.rglob("*")
            if path.is_file() and not excluded_parts.intersection(path.relative_to(ROOT).parts)
        )
    return [item.decode("utf-8") for item in result.stdout.split(b"\0") if item]


def validate_required(errors: list[str]) -> None:
    for relative in sorted(REQUIRED):
        path = ROOT / relative
        if not path.is_file() or not path.read_text("utf-8").strip():
            errors.append(f"required community file is missing or empty: {relative}")


def validate_tracked_paths(files: list[str], errors: list[str]) -> None:
    for relative in files:
        path = Path(relative)
        lowered = relative.lower()
        if path.parts and path.parts[0].lower() == "dashboard-react":
            errors.append(f"deployment-only dashboard path must not be tracked: {relative}")
        if path.name.lower() in FORBIDDEN_FILENAMES or path.name.lower().startswith(".env."):
            errors.append(f"credential/config file must not be tracked: {relative}")
        if lowered.endswith(FORBIDDEN_SUFFIXES):
            errors.append(f"private key or generated bytecode must not be tracked: {relative}")
        if "service-account" in lowered or "service_account" in lowered or "adminsdk" in lowered:
            errors.append(f"service-account path must not be tracked: {relative}")


def validate_relative_links(files: list[str], errors: list[str]) -> None:
    for relative in files:
        if not relative.lower().endswith(".md"):
            continue
        source = ROOT / relative
        text = source.read_text("utf-8")
        for raw_target in LINK_RE.findall(text):
            target = raw_target.strip().strip("<>").split(maxsplit=1)[0]
            if not target or target.startswith(("#", "http://", "https://", "mailto:")):
                continue
            target_path = unquote(target.split("#", 1)[0])
            if not target_path:
                continue
            resolved = (source.parent / target_path).resolve()
            try:
                resolved.relative_to(ROOT.resolve())
            except ValueError:
                errors.append(f"relative link escapes repository in {relative}: {target}")
                continue
            if not resolved.exists():
                errors.append(f"broken relative link in {relative}: {target}")


def validate_release_integrity(errors: list[str]) -> None:
    checksum_files = sorted((ROOT / "releases").glob("*.sha256.txt"))
    if not checksum_files:
        errors.append("no release checksum file found")
        return
    for checksum_path in checksum_files:
        parts = checksum_path.read_text("utf-8").split()
        if len(parts) < 2 or not re.fullmatch(r"[0-9a-f]{64}", parts[0]):
            errors.append(f"malformed release checksum: {checksum_path.relative_to(ROOT)}")
            continue
        archive = checksum_path.parent / parts[1].lstrip("*")
        if not archive.is_file():
            errors.append(f"checksum archive is missing: {archive.relative_to(ROOT)}")
            continue
        digest = hashlib.sha256(archive.read_bytes()).hexdigest()
        if digest != parts[0]:
            errors.append(f"release checksum mismatch: {archive.relative_to(ROOT)}")


def validate_readme_status(errors: list[str]) -> None:
    root_readme = (ROOT / "README.md").read_text("utf-8")
    required_badges = {
        "CLI security workflow": "actions/workflow/status/XbibzOfficial777/BibzCode/cli-security.yml",
        "contribution policy workflow": "actions/workflow/status/XbibzOfficial777/BibzCode/contribution-policy.yml",
        "Codacy security workflow": "actions/workflow/status/XbibzOfficial777/BibzCode/codacy.yml",
        "Python support": "Python-3.10%2B",
        "license": "github/license/XbibzOfficial777/BibzCode",
        "stars": "github/stars/XbibzOfficial777/BibzCode",
        "forks": "github/forks/XbibzOfficial777/BibzCode",
        "issues": "github/issues/XbibzOfficial777/BibzCode",
        "contributors": "github/contributors/XbibzOfficial777/BibzCode",
        "last commit": "github/last-commit/XbibzOfficial777/BibzCode",
        "repository size": "github/repo-size/XbibzOfficial777/BibzCode",
    }
    for label, marker in required_badges.items():
        if marker not in root_readme:
            errors.append(f"root README is missing the {label} badge")

    required_statistics = {
        "8 LLM providers": "<td><strong>8</strong></td>",
        "86 core tools": "<td><strong>86</strong></td>",
        "29 optional tools": "<td><strong>29</strong></td>",
        "115 maximum tools": "<td><strong>115</strong></td>",
        "56 regression tests": "<td><strong>56</strong></td>",
        "48 documentation languages": "<td><strong>48 languages</strong></td>",
        "Python support summary": "<td><code>Python 3.10+</code></td>",
        "CI matrix summary": "<td><code>3.10 · 3.13</code></td>",
    }
    for label, marker in required_statistics.items():
        if marker not in root_readme:
            errors.append(f"root README is missing the {label} statistic")

    image_tags = re.findall(r"<img\s+[^>]*>", root_readme, flags=re.IGNORECASE)
    for tag in image_tags:
        if not re.search(r'\balt="[^"]+"', tag, flags=re.IGNORECASE):
            errors.append("every root README image/badge must have descriptive alt text")


def validate_translations(errors: list[str]) -> int:
    translation_dir = ROOT / "docs" / "i18n"
    translations = sorted(translation_dir.glob("README.*.md"))
    if len(translations) < 40:
        errors.append(f"at least 40 README translations are required; found {len(translations)}")

    root_readme = (ROOT / "README.md").read_text("utf-8")
    index = (translation_dir / "README.md").read_text("utf-8")
    total_languages = len(translations) + 1  # Root README is canonical English.
    if "English (default)" not in root_readme:
        errors.append("root README must identify English as the default language")
    if f"{total_languages} languages" not in root_readme:
        errors.append("root README language count does not match translation files")
    if f"{total_languages} languages" not in index:
        errors.append("translation index language count does not match translation files")
    if (translation_dir / "README.en.md").exists():
        errors.append("English must remain the root default README, not a duplicate translation")

    for path in translations:
        relative_name = path.name
        text = path.read_text("utf-8")
        if not text.startswith("# BibzCode"):
            errors.append(f"translation must start with the BibzCode heading: {relative_name}")
        if "../../README.md" not in text:
            errors.append(f"translation must link to canonical English README: {relative_name}")
        if "bzcli" not in text:
            errors.append(f"translation must preserve the canonical command: {relative_name}")
        if f"]({relative_name})" not in index:
            errors.append(f"translation is missing from language index: {relative_name}")
        if f"docs/i18n/{relative_name}" not in root_readme:
            errors.append(f"translation is missing from root language selector: {relative_name}")

    indonesian = translation_dir / "README.id.md"
    if indonesian.is_file() and len(indonesian.read_text("utf-8")) < 5000:
        errors.append("Bahasa Indonesia README must retain extended documentation coverage")
    return total_languages


def validate_ide(files: list[str], errors: list[str]) -> None:
    package_path = ROOT / "ide" / "package.json"
    try:
        package = json.loads(package_path.read_text("utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        errors.append(f"IDE package metadata is invalid: {error}")
        return

    if package.get("name") != "bibzcode-ide" or package.get("build", {}).get("appId") != "com.bibzcode.ide":
        errors.append("IDE canonical package or application identity is invalid")
    scripts = package.get("scripts", {})
    for name in ("typecheck", "lint", "test", "test:e2e", "dist:linux", "dist:windows", "dist:mac"):
        if name not in scripts:
            errors.append(f"IDE package is missing required script: {name}")
    build = package.get("build", {})
    serialized_build = json.dumps(build, sort_keys=True)
    for marker in ("deb", "rpm", "nsis", "portable", "dmg", "zip", "universal"):
        if marker not in serialized_build and marker not in " ".join(map(str, scripts.values())):
            errors.append(f"IDE packaging configuration is missing target: {marker}")

    main_source = (ROOT / "ide" / "electron" / "main.ts").read_text("utf-8")
    for marker in ("nodeIntegration: false", "contextIsolation: true", "sandbox: true", "webSecurity: true"):
        if marker not in main_source:
            errors.append(f"IDE secure BrowserWindow setting is missing: {marker}")
    if "nodeIntegration: true" in main_source or "contextIsolation: false" in main_source:
        errors.append("IDE renderer security boundary is explicitly disabled")
    if "bibzcode://app/index.html" not in main_source or "protocol.handle('bibzcode'" not in main_source:
        errors.append("IDE must serve renderer assets through the secure custom protocol")

    fuses = (ROOT / "ide" / "scripts" / "fuses.mjs").read_text("utf-8")
    for marker in ("RunAsNode]: false", "EnableNodeOptionsEnvironmentVariable]: false", "OnlyLoadAppFromAsar]: true", "GrantFileProtocolExtraPrivileges]: false"):
        if marker not in fuses:
            errors.append(f"IDE hardened Electron fuse is missing: {marker}")

    preload = (ROOT / "ide" / "electron" / "preload.ts").read_text("utf-8")
    if "contextBridge.exposeInMainWorld" not in preload or "ipcRenderer.send(" in preload:
        errors.append("IDE preload must expose a narrow invoke-only context bridge")

    for icon in ("icon.png", "icon.ico", "icon.icns", "logo-original.png"):
        path = ROOT / "ide" / "build" / icon
        if not path.is_file() or path.stat().st_size < 1024:
            errors.append(f"IDE production icon is missing or invalid: ide/build/{icon}")

    forbidden_prefixes = ("ide/release/", "ide/dist-electron/", "ide/dist-renderer/", "ide/node_modules/")
    for relative in files:
        if relative.startswith(forbidden_prefixes):
            errors.append(f"generated IDE output must not be tracked: {relative}")

    workflow = (ROOT / ".github" / "workflows" / "ide-release.yml").read_text("utf-8")
    for marker in ("ubuntu-24.04-arm", "windows-2025", "macos-14", "WIN_CSC_LINK", "APPLE_TEAM_ID"):
        if marker not in workflow:
            errors.append(f"IDE native release workflow is missing: {marker}")


def validate_canonical_identity(errors: list[str]) -> None:
    pyproject = (ROOT / "pyproject.toml").read_text("utf-8")
    if 'name = "bibzcode-cli-agent"' not in pyproject:
        errors.append("canonical Python distribution name is missing")
    if 'bzcli = "bibzcode.__main__:main"' not in pyproject:
        errors.append("canonical bzcli entry point is missing")
    if 'dscli = "bibzcode.__main__:main"' not in pyproject:
        errors.append("documented dscli compatibility entry point is missing")

    dependabot = (ROOT / ".github/dependabot.yml").read_text("utf-8")
    if 'package-ecosystem: ""' in dependabot or "package-ecosystem: ''" in dependabot:
        errors.append("Dependabot contains an empty package ecosystem")
    if "target-branch: nightly" not in dependabot:
        errors.append("Dependabot updates must target the integration branch")


def main() -> int:
    errors: list[str] = []
    files = tracked_files()
    validate_required(errors)
    validate_tracked_paths(files, errors)
    validate_relative_links(files, errors)
    validate_release_integrity(errors)
    validate_readme_status(errors)
    total_languages = validate_translations(errors)
    validate_ide(files, errors)
    validate_canonical_identity(errors)
    if errors:
        print("Contribution policy validation failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1
    print(
        f"Contribution policy validation passed: {len(files)} tracked files, "
        f"{len(REQUIRED)} required community files, {total_languages} languages."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
